"""Add completion_date column to Tasks table

Revision ID: 99ec7e56985d
Revises: cf66fc93ff71
Create Date: 2024-11-01 16:23:07.310728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ec7e56985d'
down_revision = 'cf66fc93ff71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('completion_date')

    # ### end Alembic commands ###
